# Generated by Django 4.2.30 on 2026-09-01 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='seguro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_medico',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.AddField(
            model_name='paciente',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de Emergencia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Domicilio'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono / Celular'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('PACIENTE', 'Paciente'), ('MEDICO', 'Médico'), ('ADMIN', 'Administrador')], default='PACIENTE', max_length=10, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.DeleteModel(
            name='Seguro',
        ),
    ]
