# Generated by Django 4.2.30 on 2026-09-01 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0002_alter_especialidad_options_and_more'),
        ('usuarios', '0002_alter_paciente_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='clinica.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Turno de Atención',
                'verbose_name_plural': 'Turnos de Atención',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la Cita')),
                ('hora', models.TimeField(verbose_name='Hora de la Cita')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo de la Consulta')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clinica.medico', verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='usuarios.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'ordering': ['-fecha', '-hora'],
                'unique_together': {('medico', 'fecha', 'hora')},
            },
        ),
    ]
