# Generated by Django 4.2.30 on 2026-09-02 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Turno de Atención', 'verbose_name_plural': 'Turnos de Atención'},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha del Turno'),
        ),
    ]
