# Generated by Django 4.2.30 on 2026-09-01 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='telefono_institucional',
        ),
        migrations.AddField(
            model_name='medico',
            name='consultorio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Consultorio'),
        ),
        migrations.AddField(
            model_name='medico',
            name='licencia_medica',
            field=models.CharField(default='0000', max_length=50, unique=True, verbose_name='Licencia / Matrícula Médica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='clinica.especialidad', verbose_name='Especialidad'),
        ),
    ]
