# Generated by Django 4.2.30 on 2026-09-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_especialidad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='duracion_cita',
            field=models.PositiveIntegerField(default=30, verbose_name='Duración por cita (minutos)'),
        ),
        migrations.AddField(
            model_name='medico',
            name='max_horas_mes',
            field=models.PositiveIntegerField(default=120, verbose_name='Máximo horas al mes'),
        ),
    ]
